# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53f5aed71424022239297d0f339da54da44584df5b968e881b423de60837ea7f314fb426c3e1ab18b7f2f7f9006aa5f8f62159520c8b45632ba878c0b8dfc4c6

test:
  secret_key_base: 4582cde70c4293d361de1bece55b4228ac23e91ba434590ec3c701a40e242b2bbfe1d2c4d7cfde4cd49fdcbfd8f0e114beae2b2c82051986a7c65b8fc2573770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
